---
title: "ServerPanel Commands"
description: "Full list of commands for the ServerPanel plugin with usage examples."
sidebar_position: 4
---

# ServerPanel Commands

## Overview

ServerPanel commands fall into three groups: player commands for opening the menu (configurable), admin commands for management, and internal installer commands.

## Player Commands

Menu commands are set by the admin for each category. When you create a category, you specify one or more commands that players can use to open the menu.

### Usage

```
/(command)
```

The player types a command in chat and the menu opens to that category.

**Typical examples:**

| Command | What opens |
|---|---|
| `/menu` | Server menu main page |
| `/info` | Server information |
| `/rules` | Server rules |
| `/shop` | Shop (if integrated) |
| `/donate` | Donation info |

:::info Note
These are just examples. Your actual commands depend on how the admin set up the menu categories. Each category can have multiple commands.
:::

### Restriction Messages

Players may see these messages:

| Message | Reason |
|---|---|
| "You can't open the menu: you are in a building blocked zone!" | Player is in a building-blocked area |
| "You can't open the menu: raid block!" | Player is under raid block |
| "You can't open the menu: combat block!" | Player is under combat block |
| "You don't have access!" | Player doesn't have the required category permission |

## Admin Commands

### Template Installer

```
serverpanelinstaller.open
```

**Required permission:** `serverpanelinstaller.admin`

Opens the template installer UI. Lets you pick and install a ready-made menu design.

---

### Data Migration

```
sp.migrations list
```

Shows all available migrations. Run from the server (RCON) console.

```
sp.migrations run [name]
```

Runs the specified data migration. Used when updating the plugin and the data format has changed.

**Example:**
```
sp.migrations run all
```

:::warning Warning
Migrations can only be run from the server console (RCON). Back up your data before migrating.
:::

## Edit Mode (built-in visual editor)

**Required permission:** `serverpanel.edit`

Admins with edit permission see special buttons in the menu UI.

### Entering Edit Mode

1. Open the menu on the server.
2. Click the edit mode button in the category area.
3. The UI switches to admin mode.

### Available Actions in Edit Mode

#### Working with Categories

| Action | Description |
|---|---|
| Add category | Create a new menu category |
| Delete category | Remove a category (can't delete the last one) |
| Reorder | Move a category |
| Configure | Change name, commands, permissions, visibility |

#### Working with Pages

| Action | Description |
|---|---|
| NEW PAGE | Add a new page to the current category |
| DELETE PAGE | Delete the current page (can't delete the last one) |
| CLONE PAGE | Duplicate the current page |
| MOVE PAGE | Move a page |

#### Working with Elements

| Action | Description |
|---|---|
| Add element | Place text, an image, or a button on the page |
| Edit element | Change content, position, size, font, color |
| Delete element | Remove an element from the page |
| Move | Drag an element to a new position |

#### Working with the Header

| Action | Description |
|---|---|
| Edit header | Modify elements in the top part of the menu |
| Edit pop-ups | Open the Pop-Ups editor (requires ServerPanelPopUps) |

### Page Types

| Type | Description |
|---|---|
| UI (interface) | A page with visual elements you place through the editor |
| Plugin | A page whose content is generated by another plugin |

:::tip Tip
The "Plugin" type lets you embed other plugins right inside the ServerPanel menu. The specified plugin gets called to generate the page content.
:::

## Internal Console Commands

These commands are used by the UI automatically and aren't meant for manual input:

| Command | Description |
|---|---|
| `UI_ServerPanel` | Main command for processing UI actions |
| `UI_ServerPanel_Close` | Close the menu |
| `UI_ServerPanel_Send_Command` | Execute a command from the UI |
| `serverpanel_broadcastvideo` | Play video from the UI |

:::warning Warning
Don't use internal commands manually -- they're meant for the UI and may cause unexpected behavior.
:::
